name: CI Workflow

on: [push]

jobs:
  build-and-run:

    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
      options: --privileged
        dremio:
          image: docker pull ghcr.io/rsvihladremio/dremio-oss-test-image:latest
            ports:
              - 9047:9047
              - 32010:32010

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start Dremio service
      run: |
        docker run -d --name=dremio -p 9047:9047 -p 32010:32010 -v ${{ github.workspace }}/pkg/protocol/testdata/dremio.conf:/opt/dremio/conf/dremio.conf dremio/dremio-oss

    - name: Wait for Dremio service
      run: |
          for i in {1..90}; do
            if nc -z localhost 9047; then
              echo "Dremio service is up"
              break
            fi
            echo "Waiting for Dremio service..."
            sleep 1
          done

    - name: Build, Setup and Run
      run: |
        docker run -v $PWD:/app -w /app --platform=linux/amd64 fedora:38 /bin/bash -c "\
            dnf -y install wget unixODBC unixODBC-devel go && \
            wget https://download.dremio.com/arrow-flight-sql-odbc-driver/arrow-flight-sql-odbc-driver-LATEST.x86_64.rpm && \
            dnf -y install ./arrow-flight-sql-odbc-driver-LATEST.x86_64.rpm && \
            cd /usr/lib64/ && \
            ln -s libodbcinst.so.2.0.0 libodbcinst.so.1 && \
            ln -s libodbc.so.2.0.0 libodbc.so.1 && \
            ldconfig && \
            cd /app && \
            ./script/test && \
            ./script/lint && \
            ./script/build"
